/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables;


import com.sunnymix.flylint.api.common.jooq.converter.LocalDateTimeToOffsetDateTimeConverter;
import com.sunnymix.flylint.dao.jooq.Flylint;
import com.sunnymix.flylint.dao.jooq.Indexes;
import com.sunnymix.flylint.dao.jooq.Keys;
import com.sunnymix.flylint.dao.jooq.tables.records.RowRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Row extends TableImpl<RowRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>flylint.row</code>
     */
    public static final Row ROW = new Row();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RowRecord> getRecordType() {
        return RowRecord.class;
    }

    /**
     * The column <code>flylint.row.id</code>. ID
     */
    public final TableField<RowRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "ID");

    /**
     * The column <code>flylint.row.sheet</code>. 表格
     */
    public final TableField<RowRecord, String> SHEET = createField(DSL.name("sheet"), SQLDataType.VARCHAR(100).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "表格");

    /**
     * The column <code>flylint.row.row</code>. 行
     */
    public final TableField<RowRecord, Integer> ROW_ = createField(DSL.name("row"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "行");

    /**
     * The column <code>flylint.row.height</code>. 高度
     */
    public final TableField<RowRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("30", SQLDataType.INTEGER)), this, "高度");

    /**
     * The column <code>flylint.row.created</code>. 创建时间
     */
    public final TableField<RowRecord, OffsetDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间", new LocalDateTimeToOffsetDateTimeConverter());

    /**
     * The column <code>flylint.row.updated</code>. 更新时间
     */
    public final TableField<RowRecord, OffsetDateTime> UPDATED = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "更新时间", new LocalDateTimeToOffsetDateTimeConverter());

    private Row(Name alias, Table<RowRecord> aliased) {
        this(alias, aliased, null);
    }

    private Row(Name alias, Table<RowRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>flylint.row</code> table reference
     */
    public Row(String alias) {
        this(DSL.name(alias), ROW);
    }

    /**
     * Create an aliased <code>flylint.row</code> table reference
     */
    public Row(Name alias) {
        this(alias, ROW);
    }

    /**
     * Create a <code>flylint.row</code> table reference
     */
    public Row() {
        this(DSL.name("row"), null);
    }

    public <O extends Record> Row(Table<O> child, ForeignKey<O, RowRecord> key) {
        super(child, key, ROW);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Flylint.FLYLINT;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROW_UK_CELL);
    }

    @Override
    public Identity<RowRecord, Long> getIdentity() {
        return (Identity<RowRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RowRecord> getPrimaryKey() {
        return Keys.KEY_ROW_PRIMARY;
    }

    @Override
    public Row as(String alias) {
        return new Row(DSL.name(alias), this);
    }

    @Override
    public Row as(Name alias) {
        return new Row(alias, this);
    }

    @Override
    public Row as(Table<?> alias) {
        return new Row(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Row rename(String name) {
        return new Row(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Row rename(Name name) {
        return new Row(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Row rename(Table<?> name) {
        return new Row(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super Integer, ? super Integer, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super Integer, ? super Integer, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
