/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq;


import com.sunnymix.flylint.dao.jooq.tables.Media;
import com.sunnymix.flylint.dao.jooq.tables.Wiki;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Flylint extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>flylint</code>
     */
    public static final Flylint FLYLINT = new Flylint();

    /**
     * The table <code>flylint.media</code>.
     */
    public final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>flylint.wiki</code>.
     */
    public final Wiki WIKI = Wiki.WIKI;

    /**
     * No further instances allowed
     */
    private Flylint() {
        super("flylint", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Media.MEDIA,
            Wiki.WIKI
        );
    }
}
