/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq;


import com.sunnymix.flylint.dao.jooq.tables.Wiki;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in flylint.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index WIKI_IDX_TITLE = Internal.createIndex(DSL.name("idx_title"), Wiki.WIKI, new OrderField[] { Wiki.WIKI.TITLE }, false);
}
