/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq;


import com.sunnymix.flylint.dao.jooq.tables.Media;
import com.sunnymix.flylint.dao.jooq.tables.Wiki;
import com.sunnymix.flylint.dao.jooq.tables.records.MediaRecord;
import com.sunnymix.flylint.dao.jooq.tables.records.WikiRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * flylint.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MediaRecord> KEY_MEDIA_PRIMARY = Internal.createUniqueKey(Media.MEDIA, DSL.name("KEY_media_PRIMARY"), new TableField[] { Media.MEDIA.ID }, true);
    public static final UniqueKey<WikiRecord> KEY_WIKI_PRIMARY = Internal.createUniqueKey(Wiki.WIKI, DSL.name("KEY_wiki_PRIMARY"), new TableField[] { Wiki.WIKI.ID }, true);
    public static final UniqueKey<WikiRecord> KEY_WIKI_UK_NAME = Internal.createUniqueKey(Wiki.WIKI, DSL.name("KEY_wiki_uk_name"), new TableField[] { Wiki.WIKI.NAME }, true);
}
