/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq;


import com.sunnymix.flylint.dao.jooq.tables.Cell;
import com.sunnymix.flylint.dao.jooq.tables.Col;
import com.sunnymix.flylint.dao.jooq.tables.Media;
import com.sunnymix.flylint.dao.jooq.tables.Row;
import com.sunnymix.flylint.dao.jooq.tables.Wiki;
import com.sunnymix.flylint.dao.jooq.tables.records.CellRecord;
import com.sunnymix.flylint.dao.jooq.tables.records.ColRecord;
import com.sunnymix.flylint.dao.jooq.tables.records.MediaRecord;
import com.sunnymix.flylint.dao.jooq.tables.records.RowRecord;
import com.sunnymix.flylint.dao.jooq.tables.records.WikiRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * flylint.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CellRecord> KEY_CELL_PRIMARY = Internal.createUniqueKey(Cell.CELL, DSL.name("KEY_cell_PRIMARY"), new TableField[] { Cell.CELL.ID }, true);
    public static final UniqueKey<ColRecord> KEY_COL_PRIMARY = Internal.createUniqueKey(Col.COL, DSL.name("KEY_col_PRIMARY"), new TableField[] { Col.COL.ID }, true);
    public static final UniqueKey<MediaRecord> KEY_MEDIA_PRIMARY = Internal.createUniqueKey(Media.MEDIA, DSL.name("KEY_media_PRIMARY"), new TableField[] { Media.MEDIA.ID }, true);
    public static final UniqueKey<RowRecord> KEY_ROW_PRIMARY = Internal.createUniqueKey(Row.ROW, DSL.name("KEY_row_PRIMARY"), new TableField[] { Row.ROW.ID }, true);
    public static final UniqueKey<WikiRecord> KEY_WIKI_PRIMARY = Internal.createUniqueKey(Wiki.WIKI, DSL.name("KEY_wiki_PRIMARY"), new TableField[] { Wiki.WIKI.ID }, true);
    public static final UniqueKey<WikiRecord> KEY_WIKI_UK_NAME = Internal.createUniqueKey(Wiki.WIKI, DSL.name("KEY_wiki_uk_name"), new TableField[] { Wiki.WIKI.NAME }, true);
}
