/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq;


import com.sunnymix.flylint.dao.jooq.tables.Cell;
import com.sunnymix.flylint.dao.jooq.tables.Col;
import com.sunnymix.flylint.dao.jooq.tables.Media;
import com.sunnymix.flylint.dao.jooq.tables.Row;
import com.sunnymix.flylint.dao.jooq.tables.Wiki;


/**
 * Convenience access to all tables in flylint.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>flylint.cell</code>.
     */
    public static final Cell CELL = Cell.CELL;

    /**
     * The table <code>flylint.col</code>.
     */
    public static final Col COL = Col.COL;

    /**
     * The table <code>flylint.media</code>.
     */
    public static final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>flylint.row</code>.
     */
    public static final Row ROW = Row.ROW;

    /**
     * The table <code>flylint.wiki</code>.
     */
    public static final Wiki WIKI = Wiki.WIKI;
}
