/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq;


import com.sunnymix.flylint.dao.jooq.tables.Wiki;


/**
 * Convenience access to all tables in flylint.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>flylint.wiki</code>.
     */
    public static final Wiki WIKI = Wiki.WIKI;
}
