/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.records;


import com.sunnymix.flylint.dao.jooq.tables.Cell;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CellRecord extends UpdatableRecordImpl<CellRecord> implements Record12<Long, String, String, Integer, Integer, Integer, Integer, Integer, Integer, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>flylint.cell.id</code>. ID
     */
    public CellRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>flylint.cell.type</code>. 类型
     */
    public CellRecord setType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.type</code>. 类型
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flylint.cell.sheet</code>. 表格
     */
    public CellRecord setSheet(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.sheet</code>. 表格
     */
    public String getSheet() {
        return (String) get(2);
    }

    /**
     * Setter for <code>flylint.cell.col</code>. 列
     */
    public CellRecord setCol(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.col</code>. 列
     */
    public Integer getCol() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>flylint.cell.row</code>. 行
     */
    public CellRecord setRow(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.row</code>. 行
     */
    public Integer getRow() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>flylint.cell.col_size</code>. 列数
     */
    public CellRecord setColSize(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.col_size</code>. 列数
     */
    public Integer getColSize() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>flylint.cell.row_size</code>. 行数
     */
    public CellRecord setRowSize(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.row_size</code>. 行数
     */
    public Integer getRowSize() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>flylint.cell.width</code>. 宽度
     */
    public CellRecord setWidth(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.width</code>. 宽度
     */
    public Integer getWidth() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>flylint.cell.height</code>. 高度
     */
    public CellRecord setHeight(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.height</code>. 高度
     */
    public Integer getHeight() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>flylint.cell.content</code>. 内容
     */
    public CellRecord setContent(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.content</code>. 内容
     */
    public String getContent() {
        return (String) get(9);
    }

    /**
     * Setter for <code>flylint.cell.created</code>. 创建时间
     */
    public CellRecord setCreated(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>flylint.cell.updated</code>. 更新时间
     */
    public CellRecord setUpdated(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>flylint.cell.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, Integer, Integer, Integer, Integer, Integer, Integer, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, Integer, Integer, Integer, Integer, Integer, Integer, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Cell.CELL.ID;
    }

    @Override
    public Field<String> field2() {
        return Cell.CELL.TYPE;
    }

    @Override
    public Field<String> field3() {
        return Cell.CELL.SHEET;
    }

    @Override
    public Field<Integer> field4() {
        return Cell.CELL.COL;
    }

    @Override
    public Field<Integer> field5() {
        return Cell.CELL.ROW;
    }

    @Override
    public Field<Integer> field6() {
        return Cell.CELL.COL_SIZE;
    }

    @Override
    public Field<Integer> field7() {
        return Cell.CELL.ROW_SIZE;
    }

    @Override
    public Field<Integer> field8() {
        return Cell.CELL.WIDTH;
    }

    @Override
    public Field<Integer> field9() {
        return Cell.CELL.HEIGHT;
    }

    @Override
    public Field<String> field10() {
        return Cell.CELL.CONTENT;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return Cell.CELL.CREATED;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return Cell.CELL.UPDATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getSheet();
    }

    @Override
    public Integer component4() {
        return getCol();
    }

    @Override
    public Integer component5() {
        return getRow();
    }

    @Override
    public Integer component6() {
        return getColSize();
    }

    @Override
    public Integer component7() {
        return getRowSize();
    }

    @Override
    public Integer component8() {
        return getWidth();
    }

    @Override
    public Integer component9() {
        return getHeight();
    }

    @Override
    public String component10() {
        return getContent();
    }

    @Override
    public OffsetDateTime component11() {
        return getCreated();
    }

    @Override
    public OffsetDateTime component12() {
        return getUpdated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getSheet();
    }

    @Override
    public Integer value4() {
        return getCol();
    }

    @Override
    public Integer value5() {
        return getRow();
    }

    @Override
    public Integer value6() {
        return getColSize();
    }

    @Override
    public Integer value7() {
        return getRowSize();
    }

    @Override
    public Integer value8() {
        return getWidth();
    }

    @Override
    public Integer value9() {
        return getHeight();
    }

    @Override
    public String value10() {
        return getContent();
    }

    @Override
    public OffsetDateTime value11() {
        return getCreated();
    }

    @Override
    public OffsetDateTime value12() {
        return getUpdated();
    }

    @Override
    public CellRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CellRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public CellRecord value3(String value) {
        setSheet(value);
        return this;
    }

    @Override
    public CellRecord value4(Integer value) {
        setCol(value);
        return this;
    }

    @Override
    public CellRecord value5(Integer value) {
        setRow(value);
        return this;
    }

    @Override
    public CellRecord value6(Integer value) {
        setColSize(value);
        return this;
    }

    @Override
    public CellRecord value7(Integer value) {
        setRowSize(value);
        return this;
    }

    @Override
    public CellRecord value8(Integer value) {
        setWidth(value);
        return this;
    }

    @Override
    public CellRecord value9(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public CellRecord value10(String value) {
        setContent(value);
        return this;
    }

    @Override
    public CellRecord value11(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public CellRecord value12(OffsetDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public CellRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, OffsetDateTime value11, OffsetDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CellRecord
     */
    public CellRecord() {
        super(Cell.CELL);
    }

    /**
     * Create a detached, initialised CellRecord
     */
    public CellRecord(Long id, String type, String sheet, Integer col, Integer row, Integer colSize, Integer rowSize, Integer width, Integer height, String content, OffsetDateTime created, OffsetDateTime updated) {
        super(Cell.CELL);

        setId(id);
        setType(type);
        setSheet(sheet);
        setCol(col);
        setRow(row);
        setColSize(colSize);
        setRowSize(rowSize);
        setWidth(width);
        setHeight(height);
        setContent(content);
        setCreated(created);
        setUpdated(updated);
    }

    /**
     * Create a detached, initialised CellRecord
     */
    public CellRecord(com.sunnymix.flylint.dao.jooq.tables.pojos.Cell value) {
        super(Cell.CELL);

        if (value != null) {
            setId(value.getId());
            setType(value.getType());
            setSheet(value.getSheet());
            setCol(value.getCol());
            setRow(value.getRow());
            setColSize(value.getColSize());
            setRowSize(value.getRowSize());
            setWidth(value.getWidth());
            setHeight(value.getHeight());
            setContent(value.getContent());
            setCreated(value.getCreated());
            setUpdated(value.getUpdated());
        }
    }
}
