/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.records;


import com.sunnymix.flylint.dao.jooq.tables.Col;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ColRecord extends UpdatableRecordImpl<ColRecord> implements Record6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>flylint.col.id</code>. ID
     */
    public ColRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>flylint.col.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>flylint.col.sheet</code>. 表格
     */
    public ColRecord setSheet(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>flylint.col.sheet</code>. 表格
     */
    public String getSheet() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flylint.col.col</code>. 列
     */
    public ColRecord setCol(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>flylint.col.col</code>. 列
     */
    public Integer getCol() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>flylint.col.width</code>. 宽度
     */
    public ColRecord setWidth(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>flylint.col.width</code>. 宽度
     */
    public Integer getWidth() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>flylint.col.created</code>. 创建时间
     */
    public ColRecord setCreated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>flylint.col.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>flylint.col.updated</code>. 更新时间
     */
    public ColRecord setUpdated(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>flylint.col.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Col.COL.ID;
    }

    @Override
    public Field<String> field2() {
        return Col.COL.SHEET;
    }

    @Override
    public Field<Integer> field3() {
        return Col.COL.COL_;
    }

    @Override
    public Field<Integer> field4() {
        return Col.COL.WIDTH;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Col.COL.CREATED;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Col.COL.UPDATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSheet();
    }

    @Override
    public Integer component3() {
        return getCol();
    }

    @Override
    public Integer component4() {
        return getWidth();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreated();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSheet();
    }

    @Override
    public Integer value3() {
        return getCol();
    }

    @Override
    public Integer value4() {
        return getWidth();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreated();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdated();
    }

    @Override
    public ColRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ColRecord value2(String value) {
        setSheet(value);
        return this;
    }

    @Override
    public ColRecord value3(Integer value) {
        setCol(value);
        return this;
    }

    @Override
    public ColRecord value4(Integer value) {
        setWidth(value);
        return this;
    }

    @Override
    public ColRecord value5(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ColRecord value6(OffsetDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public ColRecord values(Long value1, String value2, Integer value3, Integer value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ColRecord
     */
    public ColRecord() {
        super(Col.COL);
    }

    /**
     * Create a detached, initialised ColRecord
     */
    public ColRecord(Long id, String sheet, Integer col, Integer width, OffsetDateTime created, OffsetDateTime updated) {
        super(Col.COL);

        setId(id);
        setSheet(sheet);
        setCol(col);
        setWidth(width);
        setCreated(created);
        setUpdated(updated);
    }

    /**
     * Create a detached, initialised ColRecord
     */
    public ColRecord(com.sunnymix.flylint.dao.jooq.tables.pojos.Col value) {
        super(Col.COL);

        if (value != null) {
            setId(value.getId());
            setSheet(value.getSheet());
            setCol(value.getCol());
            setWidth(value.getWidth());
            setCreated(value.getCreated());
            setUpdated(value.getUpdated());
        }
    }
}
