/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.records;


import com.sunnymix.flylint.dao.jooq.tables.Media;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MediaRecord extends UpdatableRecordImpl<MediaRecord> implements Record7<Long, String, String, String, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>flylint.media.id</code>. ID
     */
    public MediaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>flylint.media.name</code>. Name
     */
    public MediaRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.name</code>. Name
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flylint.media.type</code>. 类型
     */
    public MediaRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.type</code>. 类型
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>flylint.media.ext</code>. 扩展名
     */
    public MediaRecord setExt(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.ext</code>. 扩展名
     */
    public String getExt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>flylint.media.url</code>. 链接
     */
    public MediaRecord setUrl(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.url</code>. 链接
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>flylint.media.created</code>. 创建时间
     */
    public MediaRecord setCreated(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>flylint.media.updated</code>. 更新时间
     */
    public MediaRecord setUpdated(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>flylint.media.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Media.MEDIA.ID;
    }

    @Override
    public Field<String> field2() {
        return Media.MEDIA.NAME;
    }

    @Override
    public Field<String> field3() {
        return Media.MEDIA.TYPE;
    }

    @Override
    public Field<String> field4() {
        return Media.MEDIA.EXT;
    }

    @Override
    public Field<String> field5() {
        return Media.MEDIA.URL;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Media.MEDIA.CREATED;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Media.MEDIA.UPDATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getExt();
    }

    @Override
    public String component5() {
        return getUrl();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreated();
    }

    @Override
    public OffsetDateTime component7() {
        return getUpdated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getExt();
    }

    @Override
    public String value5() {
        return getUrl();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreated();
    }

    @Override
    public OffsetDateTime value7() {
        return getUpdated();
    }

    @Override
    public MediaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MediaRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public MediaRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public MediaRecord value4(String value) {
        setExt(value);
        return this;
    }

    @Override
    public MediaRecord value5(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public MediaRecord value6(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public MediaRecord value7(OffsetDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public MediaRecord values(Long value1, String value2, String value3, String value4, String value5, OffsetDateTime value6, OffsetDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaRecord
     */
    public MediaRecord() {
        super(Media.MEDIA);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(Long id, String name, String type, String ext, String url, OffsetDateTime created, OffsetDateTime updated) {
        super(Media.MEDIA);

        setId(id);
        setName(name);
        setType(type);
        setExt(ext);
        setUrl(url);
        setCreated(created);
        setUpdated(updated);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(com.sunnymix.flylint.dao.jooq.tables.pojos.Media value) {
        super(Media.MEDIA);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setType(value.getType());
            setExt(value.getExt());
            setUrl(value.getUrl());
            setCreated(value.getCreated());
            setUpdated(value.getUpdated());
        }
    }
}
