/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.records;


import com.sunnymix.flylint.dao.jooq.tables.Row;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RowRecord extends UpdatableRecordImpl<RowRecord> implements Record6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>flylint.row.id</code>. ID
     */
    public RowRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>flylint.row.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>flylint.row.sheet</code>. 表格
     */
    public RowRecord setSheet(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>flylint.row.sheet</code>. 表格
     */
    public String getSheet() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flylint.row.row</code>. 行
     */
    public RowRecord setRow(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>flylint.row.row</code>. 行
     */
    public Integer getRow() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>flylint.row.height</code>. 高度
     */
    public RowRecord setHeight(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>flylint.row.height</code>. 高度
     */
    public Integer getHeight() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>flylint.row.created</code>. 创建时间
     */
    public RowRecord setCreated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>flylint.row.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>flylint.row.updated</code>. 更新时间
     */
    public RowRecord setUpdated(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>flylint.row.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Integer, Integer, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Row.ROW.ID;
    }

    @Override
    public Field<String> field2() {
        return Row.ROW.SHEET;
    }

    @Override
    public Field<Integer> field3() {
        return Row.ROW.ROW_;
    }

    @Override
    public Field<Integer> field4() {
        return Row.ROW.HEIGHT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Row.ROW.CREATED;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Row.ROW.UPDATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSheet();
    }

    @Override
    public Integer component3() {
        return getRow();
    }

    @Override
    public Integer component4() {
        return getHeight();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreated();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSheet();
    }

    @Override
    public Integer value3() {
        return getRow();
    }

    @Override
    public Integer value4() {
        return getHeight();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreated();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdated();
    }

    @Override
    public RowRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RowRecord value2(String value) {
        setSheet(value);
        return this;
    }

    @Override
    public RowRecord value3(Integer value) {
        setRow(value);
        return this;
    }

    @Override
    public RowRecord value4(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public RowRecord value5(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public RowRecord value6(OffsetDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public RowRecord values(Long value1, String value2, Integer value3, Integer value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RowRecord
     */
    public RowRecord() {
        super(Row.ROW);
    }

    /**
     * Create a detached, initialised RowRecord
     */
    public RowRecord(Long id, String sheet, Integer row, Integer height, OffsetDateTime created, OffsetDateTime updated) {
        super(Row.ROW);

        setId(id);
        setSheet(sheet);
        setRow(row);
        setHeight(height);
        setCreated(created);
        setUpdated(updated);
    }

    /**
     * Create a detached, initialised RowRecord
     */
    public RowRecord(com.sunnymix.flylint.dao.jooq.tables.pojos.Row value) {
        super(Row.ROW);

        if (value != null) {
            setId(value.getId());
            setSheet(value.getSheet());
            setRow(value.getRow());
            setHeight(value.getHeight());
            setCreated(value.getCreated());
            setUpdated(value.getUpdated());
        }
    }
}
