/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.records;


import com.sunnymix.flylint.dao.jooq.tables.Wiki;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WikiRecord extends UpdatableRecordImpl<WikiRecord> implements Record6<Long, String, String, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>flylint.wiki.id</code>. ID
     */
    public WikiRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>flylint.wiki.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>flylint.wiki.name</code>. 路径
     */
    public WikiRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>flylint.wiki.name</code>. 路径
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>flylint.wiki.title</code>. 标题
     */
    public WikiRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>flylint.wiki.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>flylint.wiki.content</code>. 内容
     */
    public WikiRecord setContent(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>flylint.wiki.content</code>. 内容
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>flylint.wiki.created</code>. 创建时间
     */
    public WikiRecord setCreated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>flylint.wiki.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>flylint.wiki.updated</code>. 更新时间
     */
    public WikiRecord setUpdated(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>flylint.wiki.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Wiki.WIKI.ID;
    }

    @Override
    public Field<String> field2() {
        return Wiki.WIKI.NAME;
    }

    @Override
    public Field<String> field3() {
        return Wiki.WIKI.TITLE;
    }

    @Override
    public Field<String> field4() {
        return Wiki.WIKI.CONTENT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Wiki.WIKI.CREATED;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Wiki.WIKI.UPDATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreated();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreated();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdated();
    }

    @Override
    public WikiRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WikiRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public WikiRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public WikiRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public WikiRecord value5(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public WikiRecord value6(OffsetDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public WikiRecord values(Long value1, String value2, String value3, String value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WikiRecord
     */
    public WikiRecord() {
        super(Wiki.WIKI);
    }

    /**
     * Create a detached, initialised WikiRecord
     */
    public WikiRecord(Long id, String name, String title, String content, OffsetDateTime created, OffsetDateTime updated) {
        super(Wiki.WIKI);

        setId(id);
        setName(name);
        setTitle(title);
        setContent(content);
        setCreated(created);
        setUpdated(updated);
    }

    /**
     * Create a detached, initialised WikiRecord
     */
    public WikiRecord(com.sunnymix.flylint.dao.jooq.tables.pojos.Wiki value) {
        super(Wiki.WIKI);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setTitle(value.getTitle());
            setContent(value.getContent());
            setCreated(value.getCreated());
            setUpdated(value.getUpdated());
        }
    }
}
