/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cell implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String type;
    private final String sheet;
    private final Integer col;
    private final Integer row;
    private final Integer colSize;
    private final Integer rowSize;
    private final Integer width;
    private final Integer height;
    private final String content;
    private final OffsetDateTime created;
    private final OffsetDateTime updated;

    public Cell(Cell value) {
        this.id = value.id;
        this.type = value.type;
        this.sheet = value.sheet;
        this.col = value.col;
        this.row = value.row;
        this.colSize = value.colSize;
        this.rowSize = value.rowSize;
        this.width = value.width;
        this.height = value.height;
        this.content = value.content;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Cell(
        Long id,
        String type,
        String sheet,
        Integer col,
        Integer row,
        Integer colSize,
        Integer rowSize,
        Integer width,
        Integer height,
        String content,
        OffsetDateTime created,
        OffsetDateTime updated
    ) {
        this.id = id;
        this.type = type;
        this.sheet = sheet;
        this.col = col;
        this.row = row;
        this.colSize = colSize;
        this.rowSize = rowSize;
        this.width = width;
        this.height = height;
        this.content = content;
        this.created = created;
        this.updated = updated;
    }

    /**
     * Getter for <code>flylint.cell.id</code>. ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>flylint.cell.type</code>. 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Getter for <code>flylint.cell.sheet</code>. 表格
     */
    public String getSheet() {
        return this.sheet;
    }

    /**
     * Getter for <code>flylint.cell.col</code>. 列
     */
    public Integer getCol() {
        return this.col;
    }

    /**
     * Getter for <code>flylint.cell.row</code>. 行
     */
    public Integer getRow() {
        return this.row;
    }

    /**
     * Getter for <code>flylint.cell.col_size</code>. 列数
     */
    public Integer getColSize() {
        return this.colSize;
    }

    /**
     * Getter for <code>flylint.cell.row_size</code>. 行数
     */
    public Integer getRowSize() {
        return this.rowSize;
    }

    /**
     * Getter for <code>flylint.cell.width</code>. 宽度
     */
    public Integer getWidth() {
        return this.width;
    }

    /**
     * Getter for <code>flylint.cell.height</code>. 高度
     */
    public Integer getHeight() {
        return this.height;
    }

    /**
     * Getter for <code>flylint.cell.content</code>. 内容
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Getter for <code>flylint.cell.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return this.created;
    }

    /**
     * Getter for <code>flylint.cell.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return this.updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cell (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(sheet);
        sb.append(", ").append(col);
        sb.append(", ").append(row);
        sb.append(", ").append(colSize);
        sb.append(", ").append(rowSize);
        sb.append(", ").append(width);
        sb.append(", ").append(height);
        sb.append(", ").append(content);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
