/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Media implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String name;
    private final String type;
    private final String ext;
    private final String url;
    private final OffsetDateTime created;
    private final OffsetDateTime updated;

    public Media(Media value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.ext = value.ext;
        this.url = value.url;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Media(
        Long id,
        String name,
        String type,
        String ext,
        String url,
        OffsetDateTime created,
        OffsetDateTime updated
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.ext = ext;
        this.url = url;
        this.created = created;
        this.updated = updated;
    }

    /**
     * Getter for <code>flylint.media.id</code>. ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>flylint.media.name</code>. Name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>flylint.media.type</code>. 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Getter for <code>flylint.media.ext</code>. 扩展名
     */
    public String getExt() {
        return this.ext;
    }

    /**
     * Getter for <code>flylint.media.url</code>. 链接
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Getter for <code>flylint.media.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return this.created;
    }

    /**
     * Getter for <code>flylint.media.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return this.updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Media (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(ext);
        sb.append(", ").append(url);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
