/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.flylint.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Row implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String sheet;
    private final Integer row;
    private final Integer height;
    private final OffsetDateTime created;
    private final OffsetDateTime updated;

    public Row(Row value) {
        this.id = value.id;
        this.sheet = value.sheet;
        this.row = value.row;
        this.height = value.height;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Row(
        Long id,
        String sheet,
        Integer row,
        Integer height,
        OffsetDateTime created,
        OffsetDateTime updated
    ) {
        this.id = id;
        this.sheet = sheet;
        this.row = row;
        this.height = height;
        this.created = created;
        this.updated = updated;
    }

    /**
     * Getter for <code>flylint.row.id</code>. ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>flylint.row.sheet</code>. 表格
     */
    public String getSheet() {
        return this.sheet;
    }

    /**
     * Getter for <code>flylint.row.row</code>. 行
     */
    public Integer getRow() {
        return this.row;
    }

    /**
     * Getter for <code>flylint.row.height</code>. 高度
     */
    public Integer getHeight() {
        return this.height;
    }

    /**
     * Getter for <code>flylint.row.created</code>. 创建时间
     */
    public OffsetDateTime getCreated() {
        return this.created;
    }

    /**
     * Getter for <code>flylint.row.updated</code>. 更新时间
     */
    public OffsetDateTime getUpdated() {
        return this.updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Row (");

        sb.append(id);
        sb.append(", ").append(sheet);
        sb.append(", ").append(row);
        sb.append(", ").append(height);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
